### ISSUE TITLE
Traceback with latest stable and latest nightly build in LO 5.2

### ISSUE THREAD

**Issue by Ozaad** [languagetool-org/languagetool#535]
When I try to install LanguageTool with LibreOffice 5.2 (from ppa:libreoffice/libreoffice-5-2) and Oracle Java 8 on Ubuntu 16.04, I receive the following traceback:

`(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000ajava stack trace:\X000ajava.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.lang.ClassLoader.defineClass(ClassLoader.java:763)\X000a\X0009at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\X000a\X0009at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)\X000a\X0009at java.net.URLClassLoader.access$100(URLClassLoader.java:73)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:368)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:362)\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:361)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:424)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:411)\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:357)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000aCaused by: java.lang.ClassNotFoundException: com.sun.star.task.XJobExecutor\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:381)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:424)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:357)\X000a\X0009... 15 more\X000a", Context = (com.sun.star.uno.XInterface) @0 } }`

The same traceback occurs with OpenJDK 8.

**Comment by danielnaber** [comment]
Please see https://languagetool.org/issues/ and search for "Ubuntu".
